name = "charitychain/donation-tracker"
version = "1.0.0"
compiler = "v1.1.17"
plutus = "v3"
license = "MIT"
description = "Transparent donation tracking smart contracts for CharityChain platform"

[repository]
user = "charitychain"
project = "donation-tracker"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
